### ISSUE TITLE
Jira configuration via environment variables

### ISSUE THREAD

**Issue by mwarkentin** [cloudpassage-community/cp_jira_integration#2]
It'd be helpful to be able to use environment variables to configure the jira settings:

* Keep credentials (jira password) out of our github repo
* Allow us to customize the app without having to fork the repo

Thoughts?

**Comment by ashmastaflash** [comment]
Hey @mwarkentin we've published a more robust Jira <-> Halo sync tool at https://github.com/cloudpassage/jira_halo_issues_sync

The new one supports customized field mapping, transitions, and aims to place all information required to remediate issues in the Jira issue itself.
